window.PORTFOLIO_DATA = {
  "summary": {
    "gross_earned": 47991.85,
    "gambling_deposits": 17000.0,
    "gambling_withdrawals": 11525.0,
    "gambling_net_loss": -5475.0,
    "net_pocket_balance": 42516.85,
    "total_cash_inflow": 59516.85,
    "total_outflow": 17000.0
  },
  "categories": [
    {
      "id": "agency",
      "name": "Agency Salary",
      "color": "#dcf836",
      "amount": 32000.0,
      "tx_count": 4,
      "share": 66.68,
      "icon": "briefcase"
    },
    {
      "id": "college",
      "name": "College Freelance",
      "color": "#b4f044",
      "amount": 10919.0,
      "tx_count": 12,
      "share": 22.75,
      "icon": "graduation"
    },
    {
      "id": "digital",
      "name": "Digital Products",
      "color": "#f2f059",
      "amount": 4413.29,
      "tx_count": 33,
      "share": 9.2,
      "icon": "shopping-bag"
    },
    {
      "id": "razorpay",
      "name": "Razorpay Payments",
      "color": "#8ef57e",
      "amount": 569.56,
      "tx_count": 51,
      "share": 1.19,
      "icon": "credit-card"
    },
    {
      "id": "review",
      "name": "Review Work",
      "color": "#d7f283",
      "amount": 90.0,
      "tx_count": 1,
      "share": 0.19,
      "icon": "star"
    },
    {
      "id": "gambling",
      "name": "Gambling Portfolio",
      "color": "#ff5f5f",
      "amount": -5475.0,
      "tx_count": 61,
      "share": 0.0,
      "icon": "dice"
    }
  ],
  "transactions": [
    {
      "source": "Agency Salary",
      "category_id": "agency",
      "date": "June 2026",
      "iso_date": "2026-06-01",
      "time": "12:00 PM",
      "month": "June",
      "year": 2026,
      "amount": 500.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Freelance Agency Salary"
    },
    {
      "source": "Agency Salary",
      "category_id": "agency",
      "date": "July 2026",
      "iso_date": "2026-07-01",
      "time": "12:00 PM",
      "month": "July",
      "year": 2026,
      "amount": 5000.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Freelance Agency Salary"
    },
    {
      "source": "Agency Salary",
      "category_id": "agency",
      "date": "August 2026",
      "iso_date": "2026-08-01",
      "time": "12:00 PM",
      "month": "August",
      "year": 2026,
      "amount": 12500.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Freelance Agency Salary"
    },
    {
      "source": "Agency Salary",
      "category_id": "agency",
      "date": "September 2026",
      "iso_date": "2026-09-01",
      "time": "12:00 PM",
      "month": "September",
      "year": 2026,
      "amount": 14000.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Freelance Agency Salary"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-01-13",
      "iso_date": "2026-01-13",
      "time": "03:47 PM",
      "month": "January",
      "year": 2026,
      "amount": 2250.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-02-07",
      "iso_date": "2026-02-07",
      "time": "04:24 PM",
      "month": "February",
      "year": 2026,
      "amount": 899.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-02-10",
      "iso_date": "2026-02-10",
      "time": "08:09 PM",
      "month": "February",
      "year": 2026,
      "amount": 200.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-02-11",
      "iso_date": "2026-02-11",
      "time": "07:18 AM",
      "month": "February",
      "year": 2026,
      "amount": 100.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-02-11",
      "iso_date": "2026-02-11",
      "time": "08:39 AM",
      "month": "February",
      "year": 2026,
      "amount": 150.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-02-11",
      "iso_date": "2026-02-11",
      "time": "09:01 AM",
      "month": "February",
      "year": 2026,
      "amount": 270.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-02-19",
      "iso_date": "2026-02-19",
      "time": "12:32 PM",
      "month": "February",
      "year": 2026,
      "amount": 500.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-02-19",
      "iso_date": "2026-02-19",
      "time": "12:37 PM",
      "month": "February",
      "year": 2026,
      "amount": 400.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-02-20",
      "iso_date": "2026-02-20",
      "time": "11:17 PM",
      "month": "February",
      "year": 2026,
      "amount": 450.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-02-27",
      "iso_date": "2026-02-27",
      "time": "08:10 PM",
      "month": "February",
      "year": 2026,
      "amount": 2000.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-03-02",
      "iso_date": "2026-03-02",
      "time": "12:30 AM",
      "month": "March",
      "year": 2026,
      "amount": 2200.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "College Freelance",
      "category_id": "college",
      "date": "2026-03-08",
      "iso_date": "2026-03-08",
      "time": "05:59 PM",
      "month": "March",
      "year": 2026,
      "amount": 1500.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Student Freelance Project Payout"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "27-Mar-2026",
      "iso_date": "2026-03-27",
      "time": "00:03 AM",
      "month": "March",
      "year": 2026,
      "amount": 122.33,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "24-Mar-2026",
      "iso_date": "2026-03-24",
      "time": "00:03 AM",
      "month": "March",
      "year": 2026,
      "amount": 103.51,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "10-Mar-2026",
      "iso_date": "2026-03-10",
      "time": "00:03 AM",
      "month": "March",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "02-Mar-2026",
      "iso_date": "2026-03-02",
      "time": "00:03 AM",
      "month": "March",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "28-Feb-2026",
      "iso_date": "2026-02-28",
      "time": "00:02 AM",
      "month": "February",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "19-Feb-2026",
      "iso_date": "2026-02-19",
      "time": "00:02 AM",
      "month": "February",
      "year": 2026,
      "amount": 103.51,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "18-Feb-2026",
      "iso_date": "2026-02-18",
      "time": "00:02 AM",
      "month": "February",
      "year": 2026,
      "amount": 301.12,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "16-Feb-2026",
      "iso_date": "2026-02-16",
      "time": "00:02 AM",
      "month": "February",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "15-Feb-2026",
      "iso_date": "2026-02-15",
      "time": "00:02 AM",
      "month": "February",
      "year": 2026,
      "amount": 423.45,
      "type": "Credit",
      "status": "Completed",
      "details": "2 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "11-Feb-2026",
      "iso_date": "2026-02-11",
      "time": "00:02 AM",
      "month": "February",
      "year": 2026,
      "amount": 301.12,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "06-Feb-2026",
      "iso_date": "2026-02-06",
      "time": "10:02 AM",
      "month": "February",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "05-Feb-2026",
      "iso_date": "2026-02-05",
      "time": "00:02 AM",
      "month": "February",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "02-Feb-2026",
      "iso_date": "2026-02-02",
      "time": "00:02 AM",
      "month": "February",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "30-Jan-2026",
      "iso_date": "2026-01-30",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 301.12,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "29-Jan-2026",
      "iso_date": "2026-01-29",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 216.43,
      "type": "Credit",
      "status": "Completed",
      "details": "2 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "28-Jan-2026",
      "iso_date": "2026-01-28",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "26-Jan-2026",
      "iso_date": "2026-01-26",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 103.51,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "23-Jan-2026",
      "iso_date": "2026-01-23",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 103.51,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "22-Jan-2026",
      "iso_date": "2026-01-22",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 216.43,
      "type": "Credit",
      "status": "Completed",
      "details": "2 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "20-Jan-2026",
      "iso_date": "2026-01-20",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 103.51,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "18-Jan-2026",
      "iso_date": "2026-01-18",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "13-Jan-2026",
      "iso_date": "2026-01-13",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "12-Jan-2026",
      "iso_date": "2026-01-12",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 329.35,
      "type": "Credit",
      "status": "Completed",
      "details": "3 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "11-Jan-2026",
      "iso_date": "2026-01-11",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 112.92,
      "type": "Credit",
      "status": "Completed",
      "details": "1 sale(s) completed"
    },
    {
      "source": "Digital Products",
      "category_id": "digital",
      "date": "10-Jan-2026",
      "iso_date": "2026-01-10",
      "time": "00:01 AM",
      "month": "January",
      "year": 2026,
      "amount": 442.27,
      "type": "Credit",
      "status": "Completed",
      "details": "4 sale(s) completed"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "05-Apr-2026",
      "iso_date": "2026-04-05",
      "time": "22:07:23",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "06-Apr-2026",
      "iso_date": "2026-04-06",
      "time": "00:31:44",
      "month": "April",
      "year": 2026,
      "amount": 2.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "06-Apr-2026",
      "iso_date": "2026-04-06",
      "time": "13:03:16",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "08-Apr-2026",
      "iso_date": "2026-04-08",
      "time": "18:48:01",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "00:35:08",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "00:56:55",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "01:02:18",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "01:08:50",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "01:20:06",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "01:43:32",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "02:31:06",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "02:37:55",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "02:43:55",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "02:59:23",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "03:03:39",
      "month": "April",
      "year": 2026,
      "amount": 1.02,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "03:11:35",
      "month": "April",
      "year": 2026,
      "amount": 1.02,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "03:19:04",
      "month": "April",
      "year": 2026,
      "amount": 1.02,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "04:07:48",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "05:08:04",
      "month": "April",
      "year": 2026,
      "amount": 99.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "05:47:08",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "13:52:24",
      "month": "April",
      "year": 2026,
      "amount": 1.02,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "15:10:53",
      "month": "April",
      "year": 2026,
      "amount": 1.02,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "15:23:29",
      "month": "April",
      "year": 2026,
      "amount": 1.02,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "15:35:08",
      "month": "April",
      "year": 2026,
      "amount": 1.03,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "15:37:05",
      "month": "April",
      "year": 2026,
      "amount": 1.04,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "15:48:31",
      "month": "April",
      "year": 2026,
      "amount": 1.03,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "15:49:17",
      "month": "April",
      "year": 2026,
      "amount": 1.03,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "16:14:15",
      "month": "April",
      "year": 2026,
      "amount": 1.03,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "19:01:01",
      "month": "April",
      "year": 2026,
      "amount": 1.03,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "20:37:40",
      "month": "April",
      "year": 2026,
      "amount": 1.04,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "20:46:42",
      "month": "April",
      "year": 2026,
      "amount": 1.03,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "20:52:48",
      "month": "April",
      "year": 2026,
      "amount": 1.03,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "23:13:51",
      "month": "April",
      "year": 2026,
      "amount": 1.04,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "23:35:07",
      "month": "April",
      "year": 2026,
      "amount": 1.03,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "09-Apr-2026",
      "iso_date": "2026-04-09",
      "time": "23:36:22",
      "month": "April",
      "year": 2026,
      "amount": 1.03,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "10-Apr-2026",
      "iso_date": "2026-04-10",
      "time": "02:05:43",
      "month": "April",
      "year": 2026,
      "amount": 1.04,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "11-Apr-2026",
      "iso_date": "2026-04-11",
      "time": "13:45:14",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "24-Apr-2026",
      "iso_date": "2026-04-24",
      "time": "23:07:58",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "28-Apr-2026",
      "iso_date": "2026-04-28",
      "time": "19:55:21",
      "month": "April",
      "year": 2026,
      "amount": 6.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "29-Apr-2026",
      "iso_date": "2026-04-29",
      "time": "01:00:18",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "29-Apr-2026",
      "iso_date": "2026-04-29",
      "time": "11:29:17",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "30-Apr-2026",
      "iso_date": "2026-04-30",
      "time": "09:33:02",
      "month": "April",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "01-May-2026",
      "iso_date": "2026-05-01",
      "time": "11:55:48",
      "month": "May",
      "year": 2026,
      "amount": 10.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "01-May-2026",
      "iso_date": "2026-05-01",
      "time": "12:03:48",
      "month": "May",
      "year": 2026,
      "amount": 10.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "02-May-2026",
      "iso_date": "2026-05-02",
      "time": "00:17:59",
      "month": "May",
      "year": 2026,
      "amount": 6.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "02-May-2026",
      "iso_date": "2026-05-02",
      "time": "00:18:40",
      "month": "May",
      "year": 2026,
      "amount": 6.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "02-May-2026",
      "iso_date": "2026-05-02",
      "time": "10:52:08",
      "month": "May",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "27-May-2026",
      "iso_date": "2026-05-27",
      "time": "15:12:54",
      "month": "May",
      "year": 2026,
      "amount": 99.01,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "27-May-2026",
      "iso_date": "2026-05-27",
      "time": "21:01:26",
      "month": "May",
      "year": 2026,
      "amount": 180.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "31-May-2026",
      "iso_date": "2026-05-31",
      "time": "08:16:02",
      "month": "May",
      "year": 2026,
      "amount": 1.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Razorpay",
      "category_id": "razorpay",
      "date": "03-Jun-2026",
      "iso_date": "2026-06-03",
      "time": "19:36:25",
      "month": "June",
      "year": 2026,
      "amount": 110.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Razorpay Payment Gateway Capture"
    },
    {
      "source": "Review Work",
      "category_id": "review",
      "date": "June 2025",
      "iso_date": "2025-06-15",
      "time": "10:00 AM",
      "month": "June",
      "year": 2025,
      "amount": 90.0,
      "type": "Credit",
      "status": "Completed",
      "details": "Initial Product Review Bounty"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "02:54:04",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "03:47:22",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "03:56:29",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "04:03:51",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "04:12:01",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "04:56:49",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "05:17:17",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "05:35:00",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "05:43:41",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "05:45:42",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "05:52:57",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "06:00:34",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "07-Jul-2025",
      "iso_date": "2025-07-07",
      "time": "06:28:51",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "14:21:35",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "14:28:44",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "14:37:01",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "14:54:00",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "15:07:31",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "15:13:26",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "15:36:38",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "15:40:57",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "15:44:50",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "15:49:06",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "15:50:57",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "15:53:54",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Cancelled",
      "details": "Withdrawal Cancelled (Refunded at 16:58:25)"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "16:01:34",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "08-Jul-2025",
      "iso_date": "2025-07-08",
      "time": "16:58:25",
      "month": "July",
      "year": 2025,
      "amount": 450.0,
      "type": "Withdrawal",
      "status": "Cancelled",
      "details": "Reversal Credit to Casino Balance"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "09-Jul-2025",
      "iso_date": "2025-07-09",
      "time": "14:37:45",
      "month": "July",
      "year": 2025,
      "amount": -900.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "09-Jul-2025",
      "iso_date": "2025-07-09",
      "time": "14:42:58",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "09-Jul-2025",
      "iso_date": "2025-07-09",
      "time": "15:06:53",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "09-Jul-2025",
      "iso_date": "2025-07-09",
      "time": "15:10:30",
      "month": "July",
      "year": 2025,
      "amount": -450.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "09-Jul-2025",
      "iso_date": "2025-07-09",
      "time": "15:37:22",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "11-Jul-2025",
      "iso_date": "2025-07-11",
      "time": "04:10:39",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "11-Jul-2025",
      "iso_date": "2025-07-11",
      "time": "04:34:23",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "19-Jul-2025",
      "iso_date": "2025-07-19",
      "time": "04:14:22",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "19-Jul-2025",
      "iso_date": "2025-07-19",
      "time": "04:25:08",
      "month": "July",
      "year": 2025,
      "amount": -475.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "20-Jul-2025",
      "iso_date": "2025-07-20",
      "time": "07:39:29",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "26-Jul-2025",
      "iso_date": "2025-07-26",
      "time": "13:15:37",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "26-Jul-2025",
      "iso_date": "2025-07-26",
      "time": "13:49:03",
      "month": "July",
      "year": 2025,
      "amount": -503.5,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "27-Jul-2025",
      "iso_date": "2025-07-27",
      "time": "10:30:24",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "27-Jul-2025",
      "iso_date": "2025-07-27",
      "time": "11:40:55",
      "month": "July",
      "year": 2025,
      "amount": -484.5,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "28-Jul-2025",
      "iso_date": "2025-07-28",
      "time": "06:21:48",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "28-Jul-2025",
      "iso_date": "2025-07-28",
      "time": "06:30:09",
      "month": "July",
      "year": 2025,
      "amount": -494.0,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "28-Jul-2025",
      "iso_date": "2025-07-28",
      "time": "11:04:41",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "28-Jul-2025",
      "iso_date": "2025-07-28",
      "time": "11:43:37",
      "month": "July",
      "year": 2025,
      "amount": -498.75,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "29-Jul-2025",
      "iso_date": "2025-07-29",
      "time": "01:52:58",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "29-Jul-2025",
      "iso_date": "2025-07-29",
      "time": "02:07:19",
      "month": "July",
      "year": 2025,
      "amount": -500.65,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "29-Jul-2025",
      "iso_date": "2025-07-29",
      "time": "04:49:53",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "29-Jul-2025",
      "iso_date": "2025-07-29",
      "time": "05:07:52",
      "month": "July",
      "year": 2025,
      "amount": -555.75,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "29-Jul-2025",
      "iso_date": "2025-07-29",
      "time": "07:05:20",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "29-Jul-2025",
      "iso_date": "2025-07-29",
      "time": "07:19:52",
      "month": "July",
      "year": 2025,
      "amount": -712.5,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "30-Jul-2025",
      "iso_date": "2025-07-30",
      "time": "02:47:23",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "30-Jul-2025",
      "iso_date": "2025-07-30",
      "time": "03:06:12",
      "month": "July",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "04-Aug-2025",
      "iso_date": "2025-08-04",
      "time": "09:56:29",
      "month": "August",
      "year": 2025,
      "amount": -1000.35,
      "type": "Withdrawal",
      "status": "Completed",
      "details": "Bank Withdrawal"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "05-Aug-2025",
      "iso_date": "2025-08-05",
      "time": "09:53:05",
      "month": "August",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "05-Aug-2025",
      "iso_date": "2025-08-05",
      "time": "10:03:56",
      "month": "August",
      "year": 2025,
      "amount": -500.65,
      "type": "Withdrawal",
      "status": "Cancelled",
      "details": "Withdrawal Cancelled (Refunded at 10:04:05)"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "05-Aug-2025",
      "iso_date": "2025-08-05",
      "time": "10:04:05",
      "month": "August",
      "year": 2025,
      "amount": 500.65,
      "type": "Withdrawal",
      "status": "Cancelled",
      "details": "Reversal Credit to Casino Balance"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "05-Aug-2025",
      "iso_date": "2025-08-05",
      "time": "10:04:47",
      "month": "August",
      "year": 2025,
      "amount": -500.65,
      "type": "Withdrawal",
      "status": "Cancelled",
      "details": "Withdrawal Cancelled (Refunded at 10:04:56)"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "05-Aug-2025",
      "iso_date": "2025-08-05",
      "time": "10:04:56",
      "month": "August",
      "year": 2025,
      "amount": 500.65,
      "type": "Withdrawal",
      "status": "Cancelled",
      "details": "Reversal Credit to Casino Balance"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "15-Oct-2025",
      "iso_date": "2025-10-15",
      "time": "01:57:02",
      "month": "October",
      "year": 2025,
      "amount": 500.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    },
    {
      "source": "Gambling Portfolio",
      "category_id": "gambling",
      "date": "15-Oct-2025",
      "iso_date": "2025-10-15",
      "time": "12:38:55",
      "month": "October",
      "year": 2025,
      "amount": 1000.0,
      "type": "Deposit",
      "status": "Completed",
      "details": "Deposit"
    }
  ],
  "monthly_timeline": [
    {
      "month": "June",
      "year": 2025,
      "label": "June 2025",
      "short_label": "Jun '25",
      "earned": 90.0,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 90.0,
      "tx_count": 1,
      "categories_present": [
        "Review Work"
      ]
    },
    {
      "month": "July",
      "year": 2025,
      "label": "July 2025",
      "short_label": "Jul '25",
      "earned": 0,
      "gambling_net": -4475.35,
      "gambling_deposits": 15000.0,
      "gambling_withdrawals": 10524.65,
      "net_balance": -4475.35,
      "tx_count": 53,
      "categories_present": [
        "Gambling Portfolio"
      ]
    },
    {
      "month": "August",
      "year": 2025,
      "label": "August 2025",
      "short_label": "Aug '25",
      "earned": 0,
      "gambling_net": 500.35,
      "gambling_deposits": 500.0,
      "gambling_withdrawals": 1000.35,
      "net_balance": 500.35,
      "tx_count": 6,
      "categories_present": [
        "Gambling Portfolio"
      ]
    },
    {
      "month": "October",
      "year": 2025,
      "label": "October 2025",
      "short_label": "Oct '25",
      "earned": 0,
      "gambling_net": -1500.0,
      "gambling_deposits": 1500.0,
      "gambling_withdrawals": 0,
      "net_balance": -1500.0,
      "tx_count": 2,
      "categories_present": [
        "Gambling Portfolio"
      ]
    },
    {
      "month": "January",
      "year": 2026,
      "label": "January 2026",
      "short_label": "Jan '26",
      "earned": 4517.81,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 4517.81,
      "tx_count": 13,
      "categories_present": [
        "Digital Products",
        "College Freelance"
      ]
    },
    {
      "month": "February",
      "year": 2026,
      "label": "February 2026",
      "short_label": "Feb '26",
      "earned": 6662.8,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 6662.8,
      "tx_count": 18,
      "categories_present": [
        "Digital Products",
        "College Freelance"
      ]
    },
    {
      "month": "March",
      "year": 2026,
      "label": "March 2026",
      "short_label": "Mar '26",
      "earned": 4151.68,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 4151.68,
      "tx_count": 6,
      "categories_present": [
        "Digital Products",
        "College Freelance"
      ]
    },
    {
      "month": "April",
      "year": 2026,
      "label": "April 2026",
      "short_label": "Apr '26",
      "earned": 146.55,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 146.55,
      "tx_count": 42,
      "categories_present": [
        "Razorpay"
      ]
    },
    {
      "month": "May",
      "year": 2026,
      "label": "May 2026",
      "short_label": "May '26",
      "earned": 313.01,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 313.01,
      "tx_count": 8,
      "categories_present": [
        "Razorpay"
      ]
    },
    {
      "month": "June",
      "year": 2026,
      "label": "June 2026",
      "short_label": "Jun '26",
      "earned": 610.0,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 610.0,
      "tx_count": 2,
      "categories_present": [
        "Razorpay",
        "Agency Salary"
      ]
    },
    {
      "month": "July",
      "year": 2026,
      "label": "July 2026",
      "short_label": "Jul '26",
      "earned": 5000.0,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 5000.0,
      "tx_count": 1,
      "categories_present": [
        "Agency Salary"
      ]
    },
    {
      "month": "August",
      "year": 2026,
      "label": "August 2026",
      "short_label": "Aug '26",
      "earned": 12500.0,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 12500.0,
      "tx_count": 1,
      "categories_present": [
        "Agency Salary"
      ]
    },
    {
      "month": "September",
      "year": 2026,
      "label": "September 2026",
      "short_label": "Sep '26",
      "earned": 14000.0,
      "gambling_net": 0,
      "gambling_deposits": 0,
      "gambling_withdrawals": 0,
      "net_balance": 14000.0,
      "tx_count": 1,
      "categories_present": [
        "Agency Salary"
      ]
    }
  ]
};
